### ISSUE TITLE
Problém so spustením test.py

### ISSUE THREAD

**Issue by MarekVigas** [mrshu/python-imhdsk-api#2]
Ahoj som v pythone celkom nový a narazil som na tento problém keď spustím test.py.
Existuje k tomuto API aspoň nejaká dokumentácia ?

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    suggestions = imhdsk.suggest('hlavna stanica')
  File "/home/marek/python-imhdsk-api-master/imhdsk/__init__.py", line 133, in suggest
    return r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by mrshu** [comment]
@vigas147 Ahoj, toto API nema ziadnu dokumentaciu, odporucam prestudovat subor `test.py`, ktory si uz objavil.

Vdaka za report, problem bol s API pre navrhy zastavok, ktore pouzivalo zle URL. V commite, ktory je mozne vidiet vyssie bol tento problem opraveny.
